Revisão capítulos traduzidos
otaviojava/manual-arquiteto-moderno pull request #61
Opened 2021-03-30 16:12 UTC by Cibele2

Capítulos traduzidos review Cibele

2021-03-31 13:53 UTC, kmacedovarela requested changes
Obrigada pelos ajustes. Tem um pequeno detalhe a ser ajustado antes do merge.

2021-03-31 13:53 UTC, kmacedovarela commented on translation_en/about_me_PT.md
> +* **Bio:** Elder ajuda pessoas desenvolvedoras Java a trabalhar em grandes projetos, orientando-os(as) sobre como construir e entregar aplicações seguras, disponíveis e rápidasdo lado do servidor. El
```suggestion
* **Bio:** Elder ajuda pessoas desenvolvedoras Java a trabalhar em grandes projetos, orientando-os(as) sobre como construir e entregar aplicações seguras, disponíveis e rápidas do lado do servidor. Ele é o autor do Jakarta EE Cookbook e membro do conselho do SouJava, um dos maiores JUGs do mundo. Como defensor do desenvolvedor, ele compartilha experiências e melhores práticas por meio de conteúdo online e em eventos internacionais como JavaOne, The Developers Conference, QCon, Oracle Code One, Campus Party e Devnexus.
```

2021-04-05 12:41 UTC, otaviojava commented
@Cibele2 poderia resolver o conflito, por favor?

2021-04-06 08:30 UTC, otaviojava commented
Sem problemas @Cibele2 eu consigo resolver para :)

2021-04-06 08:33 UTC, otaviojava commented
Agora é sua vez :smile: 
Poderia revisar, por favor, e verificar se o conteúdo está correto?

2021-04-06 14:04 UTC, otaviojava approved these changes

2021-04-06 14:04 UTC, merged